version: '3.8'

services:
  # Infrastructure Services
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: microservices_ecom
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: ecom_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  # Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  # Microservices
  api-gateway:
    build: ./ecom-api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  order-service:
    build: ./ecom-order-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - eureka-server
      - kafka
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  inventory-service:
    build: ./inventory-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - redis
      - eureka-server
      - kafka
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  search-service:
    build: ./search-service
    ports:
      - "8086:8086"
    depends_on:
      - elasticsearch
      - eureka-server
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  payment-service:
    build: ./payment-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  product-service:
    build: ./product-service
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - eureka-server
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  cart-service:
    build: ./cart-service
    ports:
      - "8089:8089"
    depends_on:
      - redis
      - eureka-server
    env_file:
      - ./environments/dev.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_LOADBALANCER_CACHE_ENABLED=false

volumes:
  postgres_data: