version: '3.8'

services:
  # Infrastructure Services
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: microservices_ecom_staging
      POSTGRES_USER: ecom_staging_user
      POSTGRES_PASSWORD: staging_secure_password_2024
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass staging_redis_password
    volumes:
      - redis_staging_data:/data
    deploy:
      resources:
        limits:
          memory: 512M

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://staging-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          memory: 1G

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_staging_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2G

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway

  # Eureka Server
  eureka-server:
    build: ./eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M

  # Microservices
  api-gateway:
    build: ./ecom-api-gateway
    depends_on:
      - eureka-server
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M

  user-service:
    build: ./user-service
    depends_on:
      - postgres
      - eureka-server
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M

  order-service:
    build: ./ecom-order-service
    depends_on:
      - postgres
      - eureka-server
      - kafka
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M

  inventory-service:
    build: ./inventory-service
    depends_on:
      - postgres
      - redis
      - eureka-server
      - kafka
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M

  search-service:
    build: ./search-service
    depends_on:
      - elasticsearch
      - eureka-server
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M

  payment-service:
    build: ./payment-service
    depends_on:
      - eureka-server
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M

  product-service:
    build: ./product-service
    depends_on:
      - postgres
      - eureka-server
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M

  cart-service:
    build: ./cart-service
    depends_on:
      - redis
      - eureka-server
    env_file:
      - ./environments/staging.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M

volumes:
  postgres_staging_data:
  redis_staging_data:
  elasticsearch_staging_data: