# Observability Configuration Template
# Include this in service-specific application.yml files

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true
    tags:
      application: ${spring.application.name}
      environment: dev
  # OpenTelemetry Tracing Configuration - Programmatic via OpenTelemetryConfig.java
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{correlationId:-}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{correlationId:-}] [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.amar: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.security: DEBUG
    brave.sampler: DEBUG

# Spring Security OAuth2 Configuration
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/ecommerce-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/certs}

# Keycloak Configuration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  realm: ecommerce-realm
  resource: ecommerce-backend
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:backend-secret-key}
  use-resource-role-mappings: true
  # CORS handled by API Gateway - disable service-level CORS
  cors: false